### PR TITLE
Mdsplit to support ADFS (and potentially static MDQ)

### PR DESCRIPTION
**Pull request by rhoerbe**
This is an unobtrusive extension for pyff to facilitate the generation of ADFS-compatible metadata, which can be consumed like a metadata aggregate conforming to SAMLMetaIOP. Requires the c14n fix provided in a previous PR.

Doc: see src/pyff/mdsplit.py and sccripts/pyff_mdsplit.py

### CODE REVIEW

**Comment by leifj** [comment]
On 2016-07-13 21:47, Rainer Hörbe wrote:
> This is an unobtrusive extension for pyff to facilitate the generation
> of ADFS-compatible metadata, which can be consumed like a metadata
> aggregate conforming to SAMLMetaIOP. Requires the c14n fix provided in a
> previous PR.
> 
> Doc: see src/pyff/mdsplit.py and sccripts/pyff_mdsplit.py

This duplicates functionality that already exists in pyFF so I don't
think I'll merge it - at least not until I understand what this adds
beyond the existing store builtin.

**Comment by leifj** [comment]
The way I understand this it duplicates existing functions in pyFF - notably the store builtin which already stores metadata in one-entitydesciprtor-per-file. I am not going to add new cmdlines to pyFF just to wrap a particular class of pipelines.

**Comment by rhoerbe** [comment]
Maybe I did not understand how to achieve this with the builtin.

**Comment by rhoerbe** [comment]
An example or doc how to create signed per-ed files would be good

**Comment by leifj** [comment]
Skickat från min iPhone

> 13 juli 2016 kl. 22:03 skrev Rainer Hörbe <notifications@github.com>:
> 
> An example or doc how to create signed per-ed files would be good
> 
Signing each file is new but is a relatively simple pipe to write - possibly an extension to store. That pull request I would consider. I don't see the value of adding cmdline tools for this usecase though.

**Comment by leifj** [comment]
I will entertain a pull request that implements signing as an option to store but doesn't introduce a bunch of new and redundant cmdline tools.

**Comment by rhoerbe** [comment]
I might do this once I have a better understanding (or documentation) of the plumbing stuff. For the time being I will have to bear to work with the fork, which is doing the job.

**Comment by leifj** [comment]
On 2016-07-14 13:44, Rainer Hörbe wrote:
> I might do this once I have a better understanding (or documentation) of
> the plumbing stuff. For the time being I will have to bear to work with
> the fork, which is doing the job.

Pipes are fully documented using pydoc.

**Pull request closed without merging**
